# Generated by Django 3.0.8 on 2020-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=11)),
            ],
        ),
    ]
